# Generated by Django 3.0.8 on 2020-10-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_squash_init'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(choices=[('Palace Square, St. Petersburg', 'palace square, st. petersburg'), ('Online', 'online')], max_length=100),
        ),
    ]
