# Generated by Django 3.0.8 on 2020-10-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20201002_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='etype',
            field=models.CharField(choices=[('discussion', 'discussion'), ('workshop', 'workshop'), ('exhibition', 'exhibition'), ('course', 'course')], default='exhibition', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(choices=[('Online', 'online'), ('Palace Square, St. Petersburg', 'palace square, st. petersburg')], max_length=100),
        ),
    ]
