# Generated by Django 3.0.8 on 2020-10-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20201012_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='etype',
            field=models.CharField(choices=[('workshop', 'workshop'), ('discussion', 'discussion'), ('course', 'course'), ('exhibition', 'exhibition')], default='exhibition', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(choices=[('Online', 'online'), ('Palace Square, St. Petersburg', 'palace square, st. petersburg')], default='Palace Square, St. Petersburg', max_length=100),
        ),
    ]
