# Generated by Django 3.0.8 on 2020-10-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20201012_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='etype',
            field=models.CharField(choices=[('exhibition', 'exhibition'), ('discussion', 'discussion'), ('workshop', 'workshop'), ('course', 'course')], default='exhibition', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Palace Square, St. Petersburg')], default='Palace Square, St. Petersburg', max_length=100),
        ),
    ]
