# Generated by Django 3.0.8 on 2020-10-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20201013_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='etype',
            field=models.CharField(choices=[('exhibition', 'Exhibition'), ('discussion', 'Discussion'), ('workshop', 'Workshop'), ('course', 'Course')], default='exhibition', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(choices=[('all', 'All locations'), ('offline', 'Palace Square, St. Petersburg'), ('online', 'Online')], default='Palace Square, St. Petersburg', max_length=100),
        ),
    ]
