# Generated by Django 3.0.8 on 2020-11-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20201019_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(choices=[('all', 'All locations'), ('Palace Square, St. Petersburg', 'Palace Square, St. Petersburg'), ('Online', 'Online')], default='Palace Square, St. Petersburg', max_length=100),
        ),
    ]
