# Generated by Django 3.0.8 on 2020-08-26 09:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('born', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2020)])),
                ('died', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2020)])),
                ('bio', models.CharField(max_length=3000)),
            ],
        ),
    ]
