# Generated by Django 3.0.8 on 2020-08-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='born',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='artist',
            name='died',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
