# Generated by Django 3.0.8 on 2020-08-26 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20200826_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('ymade', models.PositiveIntegerField()),
                ('medium', models.CharField(max_length=100)),
                ('descr', models.CharField(max_length=3000)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Artist')),
            ],
        ),
    ]
