# Generated by Django 3.0.8 on 2020-08-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_art_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='pic',
        ),
        migrations.AlterField(
            model_name='art',
            name='descr',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='artist',
            name='bio',
            field=models.CharField(max_length=5000),
        ),
    ]
