# Generated by Django 3.0.8 on 2020-09-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20200827_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
