# Generated by Django 3.0.8 on 2020-09-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_auto_20200908_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='descr',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='bio',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
