# Generated by Django 3.0.8 on 2020-09-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0013_auto_20200930_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(choices=[('online', 'Online'), ('real', 'Palace Square, St. Petersburg')], max_length=100),
        ),
    ]
