# Generated by Django 3.0.8 on 2020-09-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0014_auto_20200930_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(choices=[('real', 'Palace Square, St. Petersburg'), ('online', 'Online')], max_length=100),
        ),
    ]
