# Generated by Django 3.0.8 on 2020-10-01 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0015_auto_20200930_1526'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
