# Generated by Django 3.0.8 on 2020-11-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0017_auto_20201001_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='wiki',
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
    ]
