# Generated by Django 3.0.8 on 2020-10-27 08:18

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0006_auto_20201019_1533'),
        ('gallery', '0017_auto_20201001_1315'),
        ('yourart', '0003_auto_20201027_0818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=accounts.models.user_path)),
                ('artworks', models.ManyToManyField(blank=True, to='gallery.Artwork')),
                ('events', models.ManyToManyField(blank=True, to='events.Event')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('yourarts', models.ManyToManyField(blank=True, to='yourart.Yourart')),
            ],
        ),
    ]
