# Generated by Django 3.0.8 on 2020-11-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='crop',
            field=models.BooleanField(default=False),
        ),
    ]
