# Generated by Django 3.0.8 on 2020-11-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_crop'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='crop_params',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
